name = "diagnostics_ooop"
version = "0.1.0"
license = "license"
author = "Timmy Jose"
maintainer = "zoltan.jose@gmail.com"
copyright = "Copyright 2026, Timmy Jose"

[features]
debug_mode.gfortran.flags = "-g -O0 -fcheck=all -fno-omit-frame-pointer -fsanitize=address,undefined -std=f2023 -Wall -Wextra -pedantic -march=native"
release_mode.gfortran.flags = "-O2 -fcheck=all -fno-omit-frame-pointer -fsanitize=address,undefined -std=f2023 -Wall -Wextra -pedantic -march=native"

[profiles]
debug = ["debug_mode"]
release = ["release_mode"]
